version: "3.9"

services:
  php :
    build: ./docker/php
    container_name: laravel-php
    volumes:
      - ./src:/var/www
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 5173:5173

  web :
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  db:
    image: mysql:8.0
    container_name: laravel-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_HOST: '%'
      TZ: 'Asia/Tokyo'

    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"

  phpmyadmin:
    container_name: laravel-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8000:80"

    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=db
      - PMA_USER=root 
      - PMA_PASSWORD=root 